language: python
python:
  - "3.5"
  - "2.7"

services:
  - postgresql
  - redis-server
  - elasticsearch
  - mariadb

env:
  - DJANGO_VERSION='1.8,<1.9' DB=sqlitefile   SEARCH=whoosh
  - DJANGO_VERSION='1.8,<1.9' DB=postgres     SEARCH=whoosh
  - DJANGO_VERSION='1.8,<1.9' DB=postgres     SEARCH=elasticsearch
  # Possible failures:
  - DJANGO_VERSION='1.8,<1.9' DB=mariadb        SEARCH=whoosh
  - DJANGO_VERSION='1.8,<1.9' DB=mariadb        SEARCH=elasticsearch
  - DJANGO_VERSION='1.8,<1.9' DB=sqlitefile   SEARCH=whoosh  VARIANT=haystack
  - DJANGO_VERSION='1.8,<1.9' DB=sqlitefile   SEARCH=elasticsearch  VARIANT=haystack

  - DJANGO_VERSION='1.10,<1.11' DB=sqlitefile   SEARCH=whoosh
#   - DJANGO_VERSION='1.10,<1.11' DB=sqlitememory
#   - DJANGO_VERSION='1.10,<1.11' DB=sqlitefile
#   - DJANGO_VERSION='1.10,<1.11' DB=postgres

before_install:
  - pip install codecov
  - pip install pep8

before_script:
# Make a MariaDB database
# Fix wierdness wiht MySQLdb on Travis - https://github.com/mozilla/kitsune/pull/2453/commits/229db28973f00dfc4fa7b386f266caf3417966a0  
  - if [[ $DB == mariadb ]]; then mysql -e 'create database aristotle_test_db;' -u root ; fi
  - if [[ $DB == mariadb ]]; then mysql -e 'SET GLOBAL wait_timeout = 36000;' ; fi
  - if [[ $DB == mariadb ]]; then mysql -e 'SET GLOBAL max_allowed_packet = 134209536;' ; fi
  - if [[ $SEARCH == elasticsearch ]]; then sleep 10; fi
  - if [[ $SEARCH == elasticsearch ]]; then pip install 'elasticsearch>2.0,<5.0'; fi
# Make a posgres database
  - if [[ $DB == postgres ]]; then psql -c 'create database aristotle_test_db;' -U postgres; fi
# Ensure PEP8 style guide is followed
  - pep8 --exclude=migrations,tests,example_mdr,'aristotle_mdr/contrib/search_backends/elasticsearch2.py' --ignore=E501,E225,E123 aristotle_mdr
# check documentation builds cleanly
  - cd docs ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ..
  - pip list

install:
  - "pip install --upgrade pip"
  - "pip uninstall setuptools -y && pip install setuptools" # needed for updated version of html5lib
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  - if [[ $DB == mariadb ]]; then pip install -q mysqlclient; fi
  - pip install 'Django>$DJANGO_VERSION' # So we can test multiple versions (once we support that)
  - "pip install -r requirements-test.txt"
  - "pip install -r requirements.txt"
  - "pip install ."
  - pip install 'Django>$DJANGO_VERSION' # So we can test multiple versions (once we support that)
# Tell us exactly what versions we are running on!

# command to run tests
script:
# Start a few workers
  - ./manage.py runworker --settings=aristotle_mdr.tests.settings.settings > worker1.log 2>&1 &
  - coverage run --branch --source=aristotle_mdr manage.py test aristotle_mdr.tests --settings=aristotle_mdr.tests.settings.settings;
  - cat worker1.log
after_success:
  - coveralls
  - codecov
  - pep8 --exclude=migrations --ignore=E501,E225,E123 aristotle_mdr

# Lets run on the new infrastructure
sudo: false

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch
  code_climate:
    repo_token: ac63d774ebdd641ef502acf1588b36248726a28a50e4e1f4ba4295a157477f54
  mariadb: '10.1'

matrix:
  allow_failures:
    - env: DJANGO_VERSION='1.8,<1.9' DB=sqlitefile   SEARCH=elasticsearch  VARIANT=haystack
    - env: DJANGO_VERSION='1.8,<1.9' DB=sqlitefile   SEARCH=whoosh  VARIANT=haystack
