sudo: false
language: python
python:
- '3.5'
install:
- pip install tox-travis
script:
- true
deploy:
  provider: pypi
  user: hwhite4
  password: uhisdfiusfisdfosdfuhsdofiusdf
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.5'
