language: python
python:
  - "2.7"
#  - "3.3" # No 3 support for notifications, yet.

services:
 #- mysql
 - postgresql
env:
  - DJ=1.8 DB=sqlitememory
  - DJ=1.8 DB=sqlitefile
  - DJ=1.8 DB=postgres
#  - DJ=1.9 DB=sqlitememory TEST=main
#  - DJ=1.9 DB=sqlitefile   TEST=main
#  - DJ=1.9 DB=postgres     TEST=main


before_install:
  - npm install -g less@1.7.4 # Required for static-precompiler
  - pip install codecov
  - pip install pep8

before_script:
# Make a posgres database, run PEP tests, check documentation builds cleanly.
#  - mysql -e 'create database aristotle_test_db;'
  - if [[ $DB == postgres ]]; then psql -c 'create database aristotle_test_db;' -U postgres; fi
  - pep8 --exclude=migrations,tests,example_mdr --ignore=E501,E225,E123 aristotle_mdr
  - cd docs ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ..

install:
  - "pip install --upgrade pip"
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --quiet; fi
#  - if [[ $DB == mysql ]]; then pip install -q mysql-python; fi
  - "pip install ."
  - pip install -q Django==$DJ
  - "pip install -r requirements-test.txt"

# command to run tests
script:
  - coverage run --branch --source=aristotle_mdr manage.py test aristotle_mdr.tests;
after_success:
  - coveralls
  - codecov
  - pep8 --exclude=migrations --ignore=E501,E225,E123 aristotle_mdr

# Lets run on the new infrastructure
sudo: false

addons:
    code_climate:
        repo_token: ac63d774ebdd641ef502acf1588b36248726a28a50e4e1f4ba4295a157477f54
