language: python
python:
#  - "2.6" # unsupported due to reportlab, which is needed for PDF downloads, not supporting 2.6.
  - "2.7"
# Python3 support to come with Django 1.7
#  - "3.2"
#  - "3.3"
# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run --branch --source=aristotle_mdr manage.py test
after_success:
  coveralls
