language: python
python:
#  - "2.6" # unsupported due to reportlab, which is needed for PDF downloads, not supporting 2.6.
  - "2.7"
#  - "3.3" # No 3 support for notifications, yet.
# command to install dependencies
before_install:
  - npm install -g less@1.7.4 # Required for static-precompiler
  - sudo pip install codecov
install:
  - "pip install coveralls"
  - pip install -q Django==$DJANGO --use-mirrors
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run --branch --source=aristotle_mdr manage.py test
after_success:
  - coveralls
  - codecov
env:
  - DJANGO=1.7
  - DJANGO=1.8
