language: python
python:
#  - "2.6" # unsupported due to reportlab, which is needed for PDF downloads, not supporting 2.6.
  - "2.7"
#  - "3.3" # No 3 support for notifications, yet.

services:
 #- mysql
 - postgresql
env:
  - DJANGO=1.7 DB=sqlitememory
  - DJANGO=1.7 DB=sqlitefile
  - DJANGO=1.7 DB=postgres
#  - DJANGO=1.7 DB=mysql
  - DJANGO=1.8 DB=sqlitememory
  - DJANGO=1.8 DB=sqlitefile
  - DJANGO=1.8 DB=postgres
#  - DJANGO=1.8 DB=mysql
before_install:
  - npm install -g less@1.7.4 # Required for static-precompiler
  - sudo pip install codecov
before_script:
#  - mysql -e 'create database modeltranslation;'
  - psql -c 'create database modeltranslation;' -U postgres
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --quiet --use-mirrors; fi
#  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - "pip install coveralls"
  - "pip install ."
  - pip install -q Django==$DJANGO --use-mirrors
  - "pip install -r requirements.txt"
  - "pip install django_tools"

# command to run tests
script:
  - coverage run --branch --source=aristotle_mdr manage.py test
after_success:
  - coveralls
  - codecov
