language: python
python:
#  - "2.6" # unsupported due to reportlab, which is needed for PDF downloads, not supporting 2.6.
  - "2.7"
#  - "3.3" # No 3 support for notifications, yet.

services:
 #- mysql
 - postgresql
env:
  - DJ=1.7 DB=sqlitememory TEST=main
  - DJ=1.7 DB=sqlitefile   TEST=main
  - DJ=1.7 DB=postgres     TEST=main
  - DJ=1.8 DB=sqlitememory TEST=main
  - DJ=1.8 DB=sqlitefile   TEST=main
  - DJ=1.8 DB=postgres     TEST=main

  - DJ=1.7 DB=sqlitememory TEST=extensions
  - DJ=1.7 DB=sqlitefile   TEST=extensions
  - DJ=1.7 DB=postgres     TEST=extensions
  - DJ=1.8 DB=sqlitememory TEST=extensions
  - DJ=1.8 DB=sqlitefile   TEST=extensions
  - DJ=1.8 DB=postgres     TEST=extensions

  - DJ=1.7 DB=sqlitememory TEST=querysets
  - DJ=1.7 DB=sqlitefile   TEST=querysets
  - DJ=1.7 DB=postgres     TEST=querysets
  - DJ=1.8 DB=sqlitememory TEST=querysets
  - DJ=1.8 DB=sqlitefile   TEST=querysets
  - DJ=1.8 DB=postgres     TEST=querysets

#  - DJ=1.7 DB=mysql
#  - DJ=1.8 DB=mysql

before_install:
  - npm install -g less@1.7.4 # Required for static-precompiler
  - sudo pip install codecov
before_script:
#  - mysql -e 'create database aristotle_test_db;'
  - pep8 --exclude=migrations --ignore=E501,E225 aristotle_mdr
  - psql -c 'create database aristotle_test_db;' -U postgres

install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --quiet --use-mirrors; fi
#  - if [[ $DB == mysql ]]; then pip install -q mysql-python --use-mirrors; fi
  - "pip install coveralls"
  - "pip install ."
  - pip install -q Django==$DJ --use-mirrors
  - "pip install -r requirements.txt"
  - "pip install django_tools"
  - "pip install pep8"

# command to run tests
script:
  - if [[ $TEST == main ]]; then coverage run --branch --source=aristotle_mdr manage.py test aristotle_mdr.tests.main; fi
  - if [[ $TEST == extensions ]]; then coverage run --branch --source=aristotle_mdr manage.py test aristotle_mdr.tests.extensions; fi
  - if [[ $TEST == querysets ]]; then coverage run --branch --source=aristotle_mdr manage.py test aristotle_mdr.tests.querysets; fi
after_success:
  - coveralls
  - codecov
