build: false

services:
  - mssql2016

environment:
  global:
    APPVEYOR: 1
  matrix:
      - DJANGO_VERSION: '1.8'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win32.whl"
      - DJANGO_VERSION: '1.8'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35-x64"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win_amd64.whl"
      - DJANGO_VERSION: '1.10'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win32.whl"
      - DJANGO_VERSION: '1.10'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35-x64"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win_amd64.whl"

install:
  - cmd: |
        set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%
        pip install tox

# command to run tests
test_script:
  - cmd: |
        tox -e py$TRAVIS_PYTHON_VERSION-django-$DJANGO_VERSION-test-windows-db-$DB-search-$SEARCH

