build: false

services:
  - mssql2016

environment:
  global:
    APPVEYOR: 1
  matrix:
      - DJANGO_VERSION: '1.8,<1.9'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win32.whl"
      - DJANGO_VERSION: '1.8,<1.9'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python35-x64"
        PYODBC_FILE: "./aristotle_mdr/tests/bin/pyodbc-3.0.10-cp35-cp35m-win_amd64.whl"
      - DJANGO_VERSION: '1.8,<1.9'
        DB: mssql
        SEARCH: whoosh
        PYTHON_HOME: "C:/Python27"
        PYODBC_FILE: pyodbc

install:
  - cmd: |
        set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%
        python -m pip install --upgrade pip
        pip install codecov
        pip install pep8
        pip install pypiwin32
        pip install setuptools -U
        pip install %PYODBC_FILE%
        pip install "django_pyodbc_azure>%DJANGO_VERSION%"
        pip install -r requirements-test.txt
        pip install -r requirements.txt
        pip install .
        pip install "Django>%DJANGO_VERSION%"

before_test:
# Make a posgres database, run PEP tests, check documentation builds cleanly.
  - cmd: |
        pip list

# command to run tests
test_script:
  - cmd: |
        python manage.py test aristotle_mdr.tests --settings=aristotle_mdr.tests.settings.settings

