build: false

services:
  - mssql2016

environment:
  global:
    PYTHON_HOME: "C:/Python27"
    APPVEYOR: 1
  matrix:
      - DJANGO_VERSION: '1.8,<1.9'
        DB: mssql
        SEARCH: whoosh
      - DJANGO_VERSION: '1.8,<1.9'
        DB: sqlitefile
        SEARCH: whoosh

install:
  - cmd: |
        "%PYTHON_HOME%/Scripts/pip.exe" install codecov
        "%PYTHON_HOME%/Scripts/pip.exe" install pep8
        "%PYTHON_HOME%/python.exe" -m pip install --upgrade pip
        "%PYTHON_HOME%/Scripts/pip.exe" install setuptools -U
        "%PYTHON_HOME%/Scripts/pip.exe" install -q "django_pyodbc_azure>%DJANGO_VERSION%"
        "%PYTHON_HOME%/Scripts/pip.exe" install -r requirements-test.txt
        "%PYTHON_HOME%/Scripts/pip.exe" install .
        "%PYTHON_HOME%/Scripts/pip.exe" install "Django>%DJANGO_VERSION%"

before_test:
# Make a posgres database, run PEP tests, check documentation builds cleanly.
  - cmd: |
        "%PYTHON_HOME%/Scripts/pip.exe" list

# command to run tests
test_script:
  - cmd: |
        "%PYTHON_HOME%/python.exe" manage.py test aristotle_mdr.tests --settings=aristotle_mdr.tests.settings.settings

