version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: aristotle_metadata_registry:dev
    command: sh ./sh/entrypoint/web.sh
    environment:
      - DJANGO_SETTINGS_MODULE=settings
      - PYTHONPATH=.
    ports:
      - "8080:8000"
    volumes:
        - ../:/usr/src/app
        - ./data:/data
